name: "Env Replace"
description: "Change environment variables during actions"
branding:
  icon: "settings"
  color: "blue"
inputs:
  key:
    description: "env key"
    required: false
  value:
    description: "env value"
    required: false
  file:
    description: "env file path"
    required: false
    default: ".env"
  replace-all:
    description: "list of key value pairs to replace"
    required: false
  upsert:
    description: "upsert key value pair"
    required: false
    default: "false"
  keep-only-replaced:
    description: "use together with replace-all: flag that determines if the result env file will contain only the replaced values"
    required: false
    default: false
runs:
  using: "node16"
  main: "dist/index.js"
